apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-backup-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:                                   # K8s secret definition
    name: gcp-cloud-storage-backup-secret   # Name of K8s secret
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID                # K8s secret key name inside secret
    remoteRef:
      key: longhorn-cloud-storage-hmac          #  GCP Secret Name
      property: access_key                      # field inside GCP Secret
  - secretKey: AWS_SECRET_ACCESS_KEY            # K8s secret key name inside secret
    remoteRef:
      key: longhorn-cloud-storage-hmac          #  GCP Secret Name
      property: access_secret
  - secretKey: AWS_ENDPOINTS                    # K8s secret key name inside secret
    remoteRef:
      key: longhorn-cloud-storage-hmac          #  GCP Secret Name
      property: endpoint
