---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.kubernetes.io/origin: |
      configuredIn: base/kustomization.yaml
      configuredBy:
        apiVersion: builtin
        kind: HelmChartInflationGenerator
  labels:
    app: longhorn-recovery-backend
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.4.0
    helm.sh/chart: longhorn-1.4.0
  name: longhorn-recovery-backend
  namespace: longhorn-system
spec:
  ports:
  - name: recovery-backend
    port: 9600
    targetPort: recov-backend
  selector:
    app: longhorn-recovery-backend
  sessionAffinity: ClientIP
  type: ClusterIP
