---
apiVersion: v1
kind: Service
metadata:
  annotations:
    config.kubernetes.io/origin: |
      configuredIn: base/kustomization.yaml
      configuredBy:
        apiVersion: builtin
        kind: HelmChartInflationGenerator
  labels:
    app: longhorn-conversion-webhook
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.4.0
    helm.sh/chart: longhorn-1.4.0
  name: longhorn-conversion-webhook
  namespace: longhorn-system
spec:
  ports:
  - name: conversion-webhook
    port: 9443
    targetPort: conversion-wh
  selector:
    app: longhorn-conversion-webhook
  sessionAffinity: ClientIP
  type: ClusterIP
